# This script generates plots from the simulations outcomes generated by 1_script.jl
# Usage:
# 1) navigate to the project directory 'rl_cheap_talk' 
# 2) run 'julia --threads NUM_THREADS scripts/2_plots.jl
#	 replacing NUM_THREADS with the desired number of threads 
#    and INPUT_DIR with the output directory of 1_script.jl 

using PGFPlotsX

include(joinpath(pwd(),"scripts","2_read_data.jl"))
extracted_data = read_data()

function plot_policy_hm(policy,xlabel,ylabel,xticklabel,yticklabel,xstep,ystep,title)
	x = repeat(1:size(policy,1), outer = size(policy,2))
	y = repeat(1:size(policy,2), inner = size(policy,1))
	coord = Coordinates(x, y; meta = vec(policy[:,end:-1:1]))
	axis = @pgf Axis(
	    {
	    	xlabel= xlabel,
	    	ylabel= ylabel,
	        enlargelimits = false,
	        xtick = (1:xstep:size(policy,1)).-0.5,
	        ytick = 1:ystep:size(policy,2),
	  	    xticklabels = xticklabel[1:xstep:end],
	        yticklabels = yticklabel[end:-ystep:1],
	        title = title,
	        point_meta_min = 0.00,
			point_meta_max = 1.0,
	        "colorbar horizontal",
			colormap= "{reversed blackwhite}{gray(0cm)=(1); gray(1cm)=(0)}",
	        "colorbar_sampled",
	        colorbar_style = raw"{scaled ticks=false, /pgf/number format/fixed, /pgf/number format/precision =5, samples = 11, at={(0.5,-0.3)}, anchor=north}",
	        ylabel_style = raw"{rotate=-90}",
	        xticklabel_style="{rotate=0}",
			width = raw"0.32\linewidth",
            height = raw"0.32\linewidth",
	    },
	    PlotInc(
	        {
	            matrix_plot,
	            mark = "",
	            point_meta = "explicit",
	            "mesh/cols" = size(policy,1)
	        },
	        coord,
	    ),
	)	
end

function plot_avg(data; legend = "", title = "", ylabel = "", color = "red", ymin = nothing, ymax = nothing, legend_pos = "", additional = "")
	average = getindex.(data, 1)
    confidence_interval = hcat(getindex.(data, 2)...)'

    xticks = 1:10:length(set_biases)
    n_biases = length(set_biases)

    pl = @pgf Axis(
        {   xlabel = raw"$b$", 
            ylabel = ylabel,
            xmin = 1, 
            xmax = n_biases,
            ymin = ymin,
            ymax = ymax, 
            title = title,
            xtick = xticks,
            xticklabels = string.(set_biases[xticks]),
            ylabel_style = "{rotate=-90}",
            scaled_y_ticks = false,
            y_tick_label_style = raw"{/pgf/number format/fixed, /pgf/number format/precision=4}",
            width = raw"0.32\linewidth",
            height = raw"0.32\linewidth",
        }
    );
    !isempty(additional) && push!(pl.options, additional)
    legend_pos == "out_bottom" && push!(pl.options, raw"xlabel style={name=xlabel}")
    legend_pos == "out_bottom" && push!(pl.options, raw"legend style={at={(0.5,-0.285)},anchor=north,legend columns = -1, column sep = 5pt}")
    legend_pos == "out_right" && push!(pl.options, raw"legend style={at={(axis description cs:1.1,0.5)},anchor=west}")
    
    @pgf pl_avg = Plot({color = color}, Table(x = 1:n_biases, y = average));
	@pgf pl_ub = Plot({"name path=f", no_marks, thin, "draw=none", "forget plot"}, Table(x = 1:n_biases, y = confidence_interval[:,1]));
	@pgf pl_lb = Plot({"name path=g", no_marks, thin, "draw=none", "forget plot"}, Table(x = 1:n_biases, y = confidence_interval[:,2]));
	@pgf pl_fill = Plot({color = color, fill = color, opacity = 0.1, "forget plot"}, raw"fill between [of=f and g]");

	push!(pl, pl_avg);
	push!(pl, pl_ub);
	push!(pl, pl_lb);
	push!(pl, pl_fill);

    !isempty(legend) && push!(pl, LegendEntry(legend))

	return pl
end

function plot_avg!(pl, data; legend = "", color = "red")
	average = getindex.(data, 1)
    confidence_interval = hcat(getindex.(data, 2)...)'

    n_biases = length(set_biases)

    @pgf pl_avg = Plot({color = color}, Table(x = 1:n_biases, y = average));
	@pgf pl_ub = Plot({"name path=f", no_marks, thin, "draw=none", "forget plot"}, Table(x = 1:n_biases, y = confidence_interval[:,1]));
	@pgf pl_lb = Plot({"name path=g", no_marks, thin, "draw=none", "forget plot"}, Table(x = 1:n_biases, y = confidence_interval[:,2]));
	@pgf pl_fill = Plot({color = color, fill = color, opacity = 0.1, "forget plot"}, raw"fill between [of=f and g]");

	push!(pl, pl_avg);
	push!(pl, pl_ub);
	push!(pl, pl_lb);
	push!(pl, pl_fill);

    !isempty(legend) && push!(pl, LegendEntry(legend))

	return pl
end

function plot_eq_bound!(pl)
	mi1 = findlast(extracted_data["best_mutual_information"] .== 1)
	mi0 = findfirst(extracted_data["best_mutual_information"] .== 0)
	@pgf pl_best_lx_bound = VLine({"draw=none", "name path=blx"}, 1)
	@pgf pl_best_rx_bound = VLine({"draw=none", "name path=brx"}, mi1)
	@pgf pl_best_fill =  Plot({color = "gray", fill = "gray", opacity = 0.08}, raw"fill between [of=blx and brx]");
	@pgf pl_worst_lx_bound =  VLine({"draw=none", "name path=wlx"}, mi0)
	@pgf pl_worst_rx_bound = VLine({"draw=none", "name path=wrx"}, length(set_biases))
	@pgf pl_worst_fill =  Plot({color = "gray", fill = "gray", opacity = 0.08}, raw"fill between [of=wlx and wrx]");
	push!(pl, pl_best_lx_bound);
	push!(pl, pl_best_rx_bound);
	push!(pl, pl_best_fill);
	push!(pl, pl_worst_lx_bound);
	push!(pl, pl_worst_rx_bound);
	push!(pl, pl_worst_fill);
end

#### ##### #### #####
#### ##### #### #####


# GENERATE PLOTS

# get outcomes of session z_ for the case of bias bias_
z_ = 1
bias_ = 0.1f0
bias_idx = findfirst(set_biases .== bias_)
avg_policy_s = extracted_data["avg_policy_s"][bias_idx][:,:,z_]
avg_policy_r = extracted_data["avg_policy_r"][bias_idx][:,:,z_]
modal_policy_s = extracted_data["modal_policy_s"][bias_idx][:,:,z_]
modal_policy_r = extracted_data["modal_policy_r"][bias_idx][:,:,z_]
avg_mean_deviation_s = extracted_data["avg_mean_deviation_s"][bias_idx][z_]
avg_mean_deviation_r = extracted_data["avg_mean_deviation_r"][bias_idx][z_]

push!(PGFPlotsX.CUSTOM_PREAMBLE, raw"\usepgfplotslibrary{fillbetween}")
hm_avg_policy_s = plot_policy_hm(avg_policy_s, raw"$\theta$", raw"$m$", string.(T), string.(1:n_messages), 4, 4, "average policy sender");
hm_avg_policy_r = plot_policy_hm(avg_policy_r, raw"$m$", raw"$a$", string.(1:n_messages), string.(A), 4, 8, "average policy receiver");
n_on_path_messages = findlast(sum(avg_policy_s,dims=1) .> 0.01)[2];
@pgf push!(hm_avg_policy_r,VLine({loosely_dashed, black}, n_on_path_messages+0.5));
@pgf push!(hm_avg_policy_s,HLine({loosely_dashed, black}, n_messages-n_on_path_messages+0.5));

pl_mean_avg_mean_deviation = plot_avg(extracted_data["mean_avg_mean_deviation_s"], color = "red", ymin = -0.001, ymax = 0.035, legend = "sender",legend_pos="out_bottom", title="mean deviation from modal policy");
pl_mean_avg_mean_deviation = plot_avg!(pl_mean_avg_mean_deviation, extracted_data["mean_avg_mean_deviation_r"], color = "blue", legend = "receiver");
pl_mean_avg_mean_deviation = plot_eq_bound!(pl_mean_avg_mean_deviation);

group_hm_policies_random_matching = @pgf GroupPlot({group_style = { group_size="2 by 1", raw"horizontal sep = 50pt" }}, hm_avg_policy_s, hm_avg_policy_r);

pdf_dir = mkpath(joinpath(input_dir,"pdf"))
tikz_dir = mkpath(joinpath(input_dir,"tikz"))
pgfsave(joinpath(tikz_dir,"avg_policy_s.tikz"),hm_avg_policy_s)
pgfsave(joinpath(pdf_dir,"avg_policy_s.pdf"),hm_avg_policy_s)
pgfsave(joinpath(tikz_dir,"avg_policy_r.tikz"),hm_avg_policy_r)
pgfsave(joinpath(pdf_dir,"avg_policy_r.pdf"),hm_avg_policy_r)
pgfsave(joinpath(tikz_dir,"mean_deviation.tikz"),pl_mean_avg_mean_deviation)
pgfsave(joinpath(pdf_dir,"mean_deviation.pdf"),pl_mean_avg_mean_deviation)
pgfsave(joinpath(tikz_dir,"group_language.tikz"),group_hm_policies_random_matching)
pgfsave(joinpath(pdf_dir,"group_language.pdf"),group_hm_policies_random_matching)

