# This reads the simulations outcomes generated by 1_script.jl and computes some metrics
# this file is loaded by 2_plots.jl

# load dependencies
using JLD2
using StatsBase
using DataStructures
using LoopVectorization
using Random
using ArgParse

# load files and functions 
macro names(arg...) string.(arg) end
include(joinpath(pwd(),"analysis.jl"))
include(joinpath(pwd(),"rl_agents.jl"))

# functions

function parse_commandline()
    arg_settings = ArgParseSettings(allow_ambiguous_opts=true)
    @add_arg_table! arg_settings begin
        # GAME SETTINGS
        "--in_dir", "-i"
            arg_type = String
            help = "input directory"
            default = "out_rand_match"
        "--step_bias"
            arg_type = Float32
            help = "space between points in [0.0,0.5]"
            default = 0.01f0
    end
    parsed_args = parse_args(arg_settings)
    return parsed_args
end

function order_policies(policy_s, policy_r)
	for i in 1:n_agents
		m_= 1
		for t in 1:n_states
			m = argmax(policy_s[t,:,i])			# index of most frequently sent message in state t
			m < m_ && continue				
			temp = policy_s[:,m_,i]
			policy_s[:,m_,i] = policy_s[:,m,i]
			policy_s[:,m,i] = temp
			temp = policy_r[m_,:,i]
			policy_r[m_,:,i] = policy_r[m,:,i]
			policy_r[m,:,i] = temp
			m_ += 1
		end
	end
	return policy_s, policy_r
end

function extract_data(config, results, best_nash, extracted_data)
	# extract and process data from data structures

	# read from files, some variavles must be global
	global bias = config["bias"]
	global reward_matrix_s, reward_matrix_r = k .* gen_reward_matrix()

	n_max_episodes = config["n_max_episodes"] 	
	Q_s = results["Q_s"];
	Q_r = results["Q_r"];
	n_episodes_s = results["n_episodes_s"];
	n_episodes_r = results["n_episodes_r"];
	n_episodes = results["n_episodes"];

	best_mutual_information = best_nash["best_mutual_information"];

	# print n_states and bias to console
	println("n_states: ", n_states, "\tbias: ", bias)

	# compute is converged bool and frequence
    #is_converged = n_episodes .< n_max_episodes
    #n_converged = count(is_converged)

	# preallocate array
 	policy_s = Array{Float32,4}(undef, n_states, n_messages, n_agents, n_simulations);
    policy_r = Array{Float32,4}(undef, n_messages, n_actions, n_agents, n_simulations);
    induced_actions = Array{Float32,5}(undef, n_states, n_actions, n_agents, n_agents, n_simulations);
	# compute metrics of interest for converged sessions
    Threads.@threads for z in 1:n_simulations
        for i in 1:n_agents
            # get policy at convergence
            policy_s[:,:,i,z] = get_policy(Q_s[:,:,i,z], temp_0*lambda_s^(n_episodes_s[i,z]-1))
            policy_r[:,:,i,z] = get_policy(Q_r[:,:,i,z], temp_0*lambda_s^(n_episodes_r[i,z]-1))
        end
        for i in 1:n_agents, j in 1:n_agents
            # get policies at convergence
            policy_s_ = policy_s[:,:,i,z]
            policy_r_ = policy_r[:,:,j,z]
            # compute induced actions at convergence
            induced_actions[:,:,i,j,z] = get_induced_actions(policy_s_, policy_r_)
            #optimal_policy_s = get_best_reply_s(policy_r_)
            #optimal_policy_r = get_best_reply_r(policy_s_)
        end
		policy_s[:,:,:,z], policy_r[:,:,:,z] = order_policies(policy_s[:,:,:,z], policy_r[:,:,:,z]);
    end

    # compute modal policies
	modal_policy_s = zeros(Float32, n_states, n_messages, n_simulations) 
	modal_policy_r = zeros(Float32, n_messages, n_actions, n_simulations) 
	Threads.@threads for z in 1:n_simulations
		for t in 1:n_states
			m = argmax(sum(policy_s[t,:,:,z], dims = 2)[:])
			modal_policy_s[t,m,z] = 1.0f0
		end
		for m in 1:n_messages
			a = argmax(sum(policy_r[m,:,:,z], dims = 2)[:])
			modal_policy_r[m,a,z] = 1.0f0
		end
	end

	# compute actions induced by the modal policy against all receivers
	modal_induced_actions = zeros(Float32, n_states, n_actions, n_agents, n_simulations);
	Threads.@threads for z in 1:n_simulations
		for t in 1:n_states
			for i in 1:n_agents
				modal_induced_actions[:,:,i,z] = modal_policy_s[:,:,z] * policy_r[:,:,i,z]
			end
		end
	end

	# average over sender-receiver pairs 
	induced_actions_ = mean(induced_actions,dims=3:4)[:,:,1,1,:]
	modal_induced_actions_ = mean(modal_induced_actions,dims=3)[:,:,1,:]

	# compute average mean deviation from mode
	#mean_deviation_s = zeros(Float32, n_states, n_agents, n_simulations) 
	#mean_deviation_r = zeros(Float32, n_messages, n_agents, n_simulations)
	avg_mean_deviation_s = zeros(Float32, n_simulations) 
	avg_mean_deviation_r = zeros(Float32, n_simulations) 
	# look at what messages are received with probability > 0.01 by senders
	# average across agents (dimension 3) and states (dimension 1) # this requires a uniform p
	support = mean(mean(policy_s,dims=3),dims=1)[1,:,1,:] .> 1e-4
	for z in 1:n_simulations
		for i in 1:n_agents
			for m in (1:n_messages)[support[:,z]]
				#mean_deviation_r = any(abs.(policy_r[m,:,i,z] - modal_policy_r[m,:,z]) .> 0.01) 
				mean_deviation_r = abs(A'policy_r[m,:,i,z] - A'modal_policy_r[m,:,z])
				avg_mean_deviation_r[z] += mean_deviation_r / (n_agents * count(support[:,z]))
			end
			for t in 1:n_states
				#mean_deviation_s = any(abs.(policy_s[t,:,i,z] - modal_policy_s[t,:,z]) .> 0.01) 
				mean_deviation_s = abs(A'induced_actions_[t,:,z] - A'modal_induced_actions_[t,:,z])
				avg_mean_deviation_s[z] += mean_deviation_s / (n_agents * n_states)
			end
		end
	end

	mean_quant(x,α) = mean(x), quantile(x, [α/2, 1-α/2])

	i = findfirst(set_biases .== bias)
	extracted_data["avg_mean_deviation_s"][i] = avg_mean_deviation_s
	extracted_data["avg_mean_deviation_r"][i] = avg_mean_deviation_r
	extracted_data["mean_avg_mean_deviation_s"][i] = mean_quant(avg_mean_deviation_s, 1.0 - α)
	extracted_data["mean_avg_mean_deviation_r"][i] = mean_quant(avg_mean_deviation_r, 1.0 - α)
	# intra session average policy
	extracted_data["avg_policy_s"][i] = dropdims(mean(policy_s,dims=3),dims=3)
	extracted_data["avg_policy_r"][i] = dropdims(mean(policy_r,dims=3),dims=3)
	extracted_data["modal_policy_s"][i] = modal_policy_s
	extracted_data["modal_policy_r"][i] = modal_policy_r
	# others
	extracted_data["best_mutual_information"][i] = best_mutual_information
end


# parse terminal config
const scrpt_config = parse_commandline()
# define set of biases 
const set_biases = Float32.(collect(0.00f0:scrpt_config["step_bias"]:0.5f0))
# define input dir 
const input_dir = joinpath(pwd(), scrpt_config["in_dir"])

# navigate to relevant subdir 
dirs = readdir(input_dir, join = true)
dirs = dirs[isdir.(dirs)]
dirs = setdiff(dirs,joinpath.(input_dir,["pdf", "temp", "tikz"]))
dir_id = 1
if length(dirs) > 1
	println("list of directories: ")
	for (dir_id, dir) in enumerate(dirs)
		println(dir_id,": ", split(dir,"/")[end])
	end
	while true
		print("select directory: ")
		global dir_id = parse(Int, readline())
		dir_id in keys(dirs) && break
	end
end
dir = dirs[dir_id]
const subdirs = readdir(dir, join=true)

# read configs that remain constant over all batches of simulations 
const config_ = load(joinpath(subdirs[2],"config.jld2"))	
const n_simulations = config_["n_simulations"]
const n_agents = config_["n_agents"]
const n_states = config_["n_states"]
const n_actions = 2 * n_states - 1
const n_messages = n_states
const T = collect(0:1f0/(n_states-1):1) 
const A = collect(0:1f0/(n_actions-1):1)
const loss_type = config_["loss"]
const k::Float32 = config_["factor"]
const dist_type = config_["dist"]
const p_t = gen_distribution()
const temp_0::Float32 = config_["temp_0"]
const lambda_s::Float32 = config_["lambda_s"]
const lambda_r::Float32 = config_["lambda_r"]

# percent of simulation outcomes to fall into confidence interval
const α = 0.95
# quantile for epsilon nash equilibria
const β = 0.9 

function read_data()
	# main loop, read files in subdirs, extract and process data, save to extracted_data
	extracted_data = DefaultDict(() -> Array{Any,1}(undef,length(set_biases)))
	for subdir in subdirs
		isdir(subdir) || continue
		config = load(joinpath(subdir,"config.jld2"))
		results = load(joinpath(subdir,"results.jld2"))
		best_nash = load(joinpath(subdir,"best_nash.jld2"))
		extract_data(config, results, best_nash, extracted_data)
	end
	return extracted_data
end
